RIDE
====

RIDE is a light-weight and intuitive editor for Robot Framework test case
files. This project is partially hosted at Google Code, the `issue
tracker`_ and Downloads_ are there.

  * Downloads_
  * Usage instructions and some tips and tricks can be found from the Wiki_
  * Bug report/enhancement request? Use the Google Code `issue tracker`_.
  * Any questions? Do not hesitate to use the `mailing list`_.
  * Development information is in `BUILD`_ file.

.. _Downloads: http://code.google.com/p/robotframework-ride/downloads/list
.. _issue tracker: http://code.google.com/p/robotframework-ride/issues/list
.. _Wiki: https://github.com/robotframework/RIDE/wiki
.. _BUILD: https://github.com/robotframework/RIDE/blob/master/BUILD.rest
.. _mailing list: http://groups.google.com/group/robotframework-users/
